services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: social_network
    ports:
      - "3307:3306"
    volumes:
      - social_mysql:/var/lib/mysql
volumes:
  social_mysql:
